Add test_token_is_allowed()
PatrickAlphaC/defi-stake-yield-brownie pull request #2
Opened 2021-12-12 00:11 UTC by moonwake769

Add `test_token_is_allowed()` in order to test the function `tokenIsAllowed()` from `contracts/TokenFarm.sol`

2021-12-13 18:46 UTC, PatrickAlphaC commented
This is a good PR! Thanks!

We just need to make that function a view function to return a bool.

2021-12-13 23:09 UTC, moonwake769 commented
Thanks for letting me know how to improve this PR!

2021-12-14 16:00 UTC, PatrickAlphaC requested changes
Just one change :)

2021-12-14 16:00 UTC, PatrickAlphaC commented on tests/unit/test_token_farm.py
> +    assert token_is_allowed == True
```suggestion
    assert token_is_allowed is True
```

2021-12-14 16:00 UTC, merged

2021-12-14 16:00 UTC, PatrickAlphaC commented
Thanks for this PR!!